# Puerto por defecto
server.port=8080

spring.application.name=user-service

# Liquibase - ruta del changelog principal
spring.liquibase.change-log=classpath:db.changelog/changelog-master.xml

# Configuración PostgreSQL (ajusta usuario/password/DB a tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres
//spring.datasource.driver-class-name=org.postgresql.Driver

# Dejar la creacion/actualizacion de esquema a Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
