# Puerto por defecto (puedes cambiarlo si quieres)
# server.port=8080

spring.application.name=user-service

# Liquibase - ruta del changelog principal
spring.liquibase.change-log=classpath:db.changelog-master.yaml

# Configuración PostgreSQL (ajusta usuario/password/DB a tu entorno)
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Dejar la creación/actualización de esquema a Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
